/**
 * Auto-generated TypeScript types from nexus-protocol Pydantic models
 * Generated on: 2025-12-19T08:57:19.660072
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run `python packages/nexus-protocol/generate_types.py` to regenerate
 */

// ============================================================================
// Enums
// ============================================================================

// ============================================================================
// Interfaces
// ============================================================================

/**
 * Complete NXML panel Abstract Syntax Tree.
 */
export interface NexusPanelAST {
  kind?: string | null;
  /** Panel metadata */
  meta: PanelMeta;
  /** Data section (state & computed) */
  data: DataAST;
  /** Logic section (tools & handlers) */
  logic: LogicAST;
  /** View section (UI tree) */
  view: ViewAST;
  loc?: SourceLocation | null | null;
}

/**
 * Metadata for a Nexus panel.
 */
export interface PanelMeta {
  /** Unique panel ID */
  id: string;
  /** Panel display title */
  title?: string | null | null;
  /** Panel type (e.g., 'custom', 'flowchart') */
  type: string;
  /** Panel schema version */
  version?: string | null;
  /** Panel description */
  description?: string | null | null;
  /** Panel author */
  author?: string | null | null;
  /** Creation timestamp */
  createdAt?: string | null | null;
  /** Searchable tags */
  tags?: Array<string>;
  /** Icon name or emoji */
  icon?: string | null | null;
}

/**
 * Data section containing state and computed values.
 */
export interface DataAST {
  kind?: string | null;
  states?: Array<StateNode>;
  computed?: Array<ComputedNode>;
  loc?: SourceLocation | null | null;
}

/**
 * Logic section containing tools, handlers, and lifecycles.
 */
export interface LogicAST {
  kind?: string | null;
  extensions?: Array<ExtensionNode>;
  tools?: Array<ToolNode>;
  lifecycles?: Array<LifecycleNode>;
  loc?: SourceLocation | null | null;
}

/**
 * View section containing the UI component tree.
 */
export interface ViewAST {
  kind?: string | null;
  /** Root component */
  root: ViewNode;
  loc?: SourceLocation | null | null;
}

/**
 * State variable declaration.
 */
export interface StateNode {
  kind?: string | null;
  /** State variable name */
  name: string;
  /** Data type */
  type: NXMLPrimitiveType;
  /** Default value */
  default?: default;
  /** State description */
  description?: string | null | null;
  /** Validation rules */
  validation?: object | null | null;
  loc?: SourceLocation | null | null;
}

/**
 * Computed value declaration (derived from state).
 */
export interface ComputedNode {
  kind?: string | null;
  /** Computed variable name */
  name: string;
  /** Expression to compute value */
  value: string;
  /** Result type */
  type?: NXMLPrimitiveType | null | null;
  /** State dependencies */
  dependencies?: Array<string>;
  /** Computed description */
  description?: string | null | null;
  loc?: SourceLocation | null | null;
}

/**
 * Tool definition (user-invokable function).
 */
export interface ToolNode {
  kind?: string | null;
  /** Tool name */
  name: string;
  /** Tool arguments */
  args?: Array<ArgNode>;
  /** Tool implementation */
  handler: HandlerNode;
  /** Tool description */
  description?: string | null | null;
  /** Tool icon */
  icon?: string | null | null;
  loc?: SourceLocation | null | null;
}

/**
 * Handler code block.
 */
export interface HandlerNode {
  kind?: string | null;
  /** JavaScript handler code */
  code: string;
  /** Required capabilities */
  capabilities?: Array<string>;
  /** Execution timeout in milliseconds */
  timeoutMs?: number | null;
  loc?: SourceLocation | null | null;
}

/**
 * Lifecycle hook definition.
 */
export interface LifecycleNode {
  kind?: string | null;
  /** Lifecycle event (mount, unmount, etc.) */
  event: string;
  /** Lifecycle handler */
  handler: HandlerNode;
  loc?: SourceLocation | null | null;
}

export interface ViewNode {
}

/**
 * Source code location for error reporting.
 */
export interface SourceLocation {
  startLine: number;
  startColumn: number;
  endLine: number;
  endColumn: number;
}

/**
 * A node in the Nexus Object Graph.
 */
export interface NOGEntity {
  /** Unique entity ID */
  id: string;
  /** Type of entity */
  entityType: EntityType;
  /** Human-readable name */
  name: string;
  /** Entity description */
  description?: string | null | null;
  /** Entity properties */
  properties?: Record<string, any>;
  /** Panel that created this entity */
  sourcePanelId?: string | null | null;
  /** Source code location */
  sourceLocation?: string | null | null;
  /** Entity version number */
  version?: number | null;
  createdAt?: string;
  updatedAt?: string;
  /** Searchable tags */
  tags?: Array<string>;
}

/**
 * An edge in the Nexus Object Graph.
 */
export interface NOGRelationship {
  /** Unique relationship ID */
  id: string;
  /** Source entity ID */
  sourceId: string;
  /** Target entity ID */
  targetId: string;
  /** Type of relationship */
  relationType: RelationType;
  /** Relationship properties */
  properties?: Record<string, any>;
  /** Relationship weight/strength */
  weight?: number | null;
  /** Is bidirectional */
  bidirectional?: boolean | null;
  createdAt?: string;
  /** Panel or user that created this */
  createdBy?: string | null | null;
}

/**
 * A complete snapshot of the NOG graph state.
 */
export interface NOGGraphSnapshot {
  /** Workspace ID */
  workspaceId: string;
  /** Workspace name */
  workspaceName: string;
  /** Snapshot version */
  version: number;
  entities?: Array<NOGEntity>;
  relationships?: Array<NOGRelationship>;
  entityCount?: number | null;
  relationshipCount?: number | null;
  /** Count by type */
  entityTypes?: Record<string, any>;
  createdAt?: string;
  /** Git commit hash */
  commitHash?: string | null | null;
}

/**
 * A patch operation to apply to the NOG.
 */
export interface NOGPatch {
  /** Type of operation */
  operation: PatchOperation;
  /** Entity ID (for entity operations) */
  entityId?: string | null | null;
  /** Relationship ID (for relationship operations) */
  relationshipId?: string | null | null;
  /** Operation data */
  data?: Record<string, any>;
  /** When the patch was applied */
  appliedAt?: string | null | null;
  /** Who applied the patch (user/panel/AI) */
  appliedBy?: string | null | null;
  /** Source of the patch (user_edit, ai_suggestion, etc.) */
  source: string;
}

/**
 * A batch of patches to apply atomically.
 */
export interface PatchBatch {
  /** List of patches */
  patches: Array<NOGPatch>;
  /** Batch description */
  description?: string | null | null;
  /** Apply all or none */
  atomic?: boolean | null;
  createdAt?: string;
  /** Creator */
  createdBy?: string | null | null;
}

/**
 * A query against the NOG graph.
 */
export interface NOGQuery {
  /** Type of query */
  queryType: string;
  /** Entity ID (for get_entity, get_subgraph) */
  entityId?: string | null | null;
  /** Source entity (for find_path) */
  sourceId?: string | null | null;
  /** Target entity (for find_path) */
  targetId?: string | null | null;
  /** Search term (for search) */
  searchTerm?: string | null | null;
  /** Filter by entity types */
  entityTypes?: array | null | null;
  /** Filter by relation types */
  relationTypes?: array | null | null;
  /** Filter by tags */
  tags?: array | null | null;
  /** Traversal depth (for get_subgraph) */
  depth?: number | null;
  /** Maximum results */
  limit?: number | null;
  /** Include entity properties */
  includeProperties?: boolean | null;
}

/**
 * Result of a NOG query.
 */
export interface NOGQueryResult {
  /** Query success */
  success: boolean;
  /** Query type */
  queryType: string;
  entities?: Array<NOGEntity>;
  relationships?: Array<NOGRelationship>;
  /** Path (for find_path) */
  path?: array | null | null;
  resultCount?: number | null;
  executionTimeMs?: number | null;
  /** Error message if failed */
  error?: string | null | null;
}

/**
 * Client requests handler execution.
 */
export interface ExecuteHandlerMessage {
  type?: string | null;
  /** Name of handler to execute */
  handlerName: string;
  /** Handler arguments */
  args?: Record<string, any>;
  /** Request ID for correlation */
  requestId?: string | null | null;
}

/**
 * Server pushes state updates.
 */
export interface StateUpdateMessage {
  type?: string | null;
  /** State mutations */
  mutations: Array<StateMutation>;
  /** Panel that changed */
  panelId?: string | null | null;
  /** Source of update (handler, AI, etc.) */
  source: string;
  timestamp?: string;
}

/**
 * Server pushes NOG graph updates.
 */
export interface NOGUpdateMessage {
  type?: string | null;
  /** Full snapshot or patch */
  updateType: string;
  /** Full graph snapshot */
  snapshot?: object | null | null;
  /** Graph patches */
  patches?: array | null | null;
  /** Graph version */
  version: number;
  timestamp?: string;
}
